# Ajustes opcionais do projeto Supabase
project_id = "egupwrwzcuqazlshhfoq"

[api]
enabled = true

[functions.transcribe]
verify_jwt = true

[functions.get-upload-url]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false
